const languages = [
{name:"指定なし",value:0},
{name:"AIR",value:1},
{name:"Androidアプリ",value:2},
{name:"ASP.net",value:3},
{name:"C#",value:4},
{name:"COBOL",value:5},
{name:"CSS",value:6},
{name:"C／C++",value:7},
{name:"Delphi",value:8},
{name:"Facebookアプリ",value:9},
{name:"Fortran",value:10},
{name:"Go",value:11},
{name:"HTML",value:12},
{name:"iPhoneアプリ",value:13},
{name:"Java",value:14},
{name:"JavaScript",value:15},
{name:"MATLAB",value:16},
{name:"MySQL",value:17},
{name:"Objective-C",value:18},
{name:"Open CV",value:19},
{name:"OpenGL",value:20},
{name:"Oracle",value:21},
{name:"Pascal",value:22},
{name:"Perl",value:23},
{name:"PHP",value:24},
{name:"Postgres",value:25},
{name:"Python",value:26},
{name:"Ruby",value:27},
{name:"R言語",value:28},
{name:"Scala",value:29},
{name:"SQL",value:30},
{name:"Swift",value:31},
{name:"Unity",value:32},
{name:"VB",value:33},
{name:"VB .net",value:34},
{name:"VBA",value:35},
{name:"VC",value:36},
]
export default languages